version: "3"
services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: goers-take-home-test-todo
    ports:
      - 6432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  todo-be:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 3000:3000
    env_file:
      - .env

volumes:
  postgres-data:
